/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.sulfin.logicsim

import com.sulfin.logicsim.app.MainWindow


fun main() {
    val window = MainWindow()

    val mainThread = Thread(window)
    mainThread.start()

}
